apiVersion: v1
kind: Secret
metadata:
  name: flashsend-secret
  namespace: flashsend-prod
type: Opaque
stringData:
  DATABASE_URL: "<DATABASE_URL>"
  AMQP_URL: "<AMQP_URL>"
  JWT_SECRET: "change-me-in-production"
  APIKEY_HMAC_SECRET: "change-me-in-production"
  SMTP_EMAIL: "your-email@gmail.com"
  SMTP_APP_PASSWORD: "your-smtp-app-password"
  TWILIO_ACCOUNT_SID: "your-twilio-sid"
  TWILIO_AUTH_TOKEN: "your-twilio-auth-token"
  TWILIO_PHONE_NUMBER: "your-twilio-phone"
  VONAGE_API_KEY: "your-vonage-api-key"
  VONAGE_API_SECRET: "your-vonage-api-secret"