apiVersion: v1
kind: Secret
metadata:
  name: flashsend-secret
  namespace: flashsend-prod
type: Opaque
stringData:
  DATABASE_URL: "postgres://flashsend:flashsend@postgres.flashsend-prod.svc.cluster.local:5432/flashsend?sslmode=disable"
  AMQP_URL: "amqp://flashsend:flashsend@rabbitmq.flashsend-prod.svc.cluster.local:5672/"
  JWT_SECRET: "change-me-in-production"
  APIKEY_HMAC_SECRET: "change-me-in-production"
  SMTP_EMAIL: "your-email@gmail.com"
  SMTP_APP_PASSWORD: "your-smtp-app-password"
  TWILIO_ACCOUNT_SID: "your-twilio-sid"
  TWILIO_AUTH_TOKEN: "your-twilio-auth-token"
  TWILIO_PHONE_NUMBER: "your-twilio-phone"
  VONAGE_API_KEY: "your-vonage-api-key"
  VONAGE_API_SECRET: "your-vonage-api-secret"